sudo mkdir /usr/binnew/
sudo cp -Rav /usr/bin/basename   /usr/binnew
sudo cp -Rav /usr/bin/cut        /usr/binnew
sudo cp -Rav /usr/bin/clear      /usr/binnew
sudo cp -Rav /usr/bin/diff       /usr/binnew
sudo cp -Rav /usr/bin/dir        /usr/binnew
sudo cp -Rav /usr/bin/dirname    /usr/binnew
sudo cp -Rav /usr/bin/du         /usr/binnew
sudo cp -Rav /usr/bin/env        /usr/binnew
sudo cp -Rav /usr/bin/expr       /usr/binnew
sudo cp -Rav /usr/bin/file       /usr/binnew
sudo cp -Rav /usr/bin/gawk       /usr/binnew
sudo cp -Rav /usr/bin/getopt     /usr/binnew
sudo cp -Rav /usr/bin/groups     /usr/binnew
sudo cp -Rav /usr/bin/iconv      /usr/binnew
sudo cp -Rav /usr/bin/id         /usr/binnew
sudo cp -Rav /usr/bin/last       /usr/binnew
sudo cp -Rav /usr/bin/lastlog    /usr/binnew
sudo cp -Rav /usr/bin/ld         /usr/binnew
sudo cp -Rav /usr/bin/ldd        /usr/binnew
sudo cp -Rav /usr/bin/lddlibc4   /usr/binnew
sudo cp -Rav /usr/bin/lrz        /usr/binnew
sudo cp -Rav /usr/bin/lsz        /usr/binnew
sudo cp -Rav /usr/bin/md5sum     /usr/binnew
sudo cp -Rav /usr/bin/nohup      /usr/binnew
sudo cp -Rav /usr/bin/php        /usr/binnew
sudo cp -Rav /usr/bin/rz         /usr/binnew
sudo cp -Rav /usr/bin/scp        /usr/binnew
sudo cp -Rav /usr/bin/sort       /usr/binnew
sudo cp -Rav /usr/bin/ssh        /usr/binnew
sudo cp -Rav /usr/bin/ssh-keygen /usr/binnew
sudo cp -Rav /usr/bin/sudo       /usr/binnew
sudo cp -Rav /usr/bin/sz         /usr/binnew
sudo cp -Rav /usr/bin/tail       /usr/binnew
sudo cp -Rav /usr/bin/tput       /usr/binnew
sudo cp -Rav /usr/bin/telnet     /usr/binnew
sudo cp -Rav /usr/bin/top        /usr/binnew
sudo cp -Rav /usr/bin/touch      /usr/binnew
sudo cp -Rav /usr/bin/unzip      /usr/binnew
sudo cp -Rav /usr/bin/uptime     /usr/binnew
sudo cp -Rav /usr/bin/vi         /usr/binnew
sudo cp -Rav /usr/bin/vim        /usr/binnew
sudo cp -Rav /usr/bin/vimdiff    /usr/binnew
sudo cp -Rav /usr/bin/w          /usr/binnew
sudo cp -Rav /usr/bin/wc         /usr/binnew
sudo cp -Rav /usr/bin/wget       /usr/binnew
sudo cp -Rav /usr/bin/whereis    /usr/binnew
sudo cp -Rav /usr/bin/which      /usr/binnew
sudo cp -Rav /usr/bin/who        /usr/binnew
sudo cp -Rav /usr/bin/whoami     /usr/binnew
sudo cp -Rav /usr/bin/xargs      /usr/binnew

sudo cp -Rav /usr/bin/my_print_defaults /usr/binnew
sudo cp -Rav /usr/bin/mysql             /usr/binnew
sudo cp -Rav /usr/bin/mysqld_safe       /usr/binnew
