#!/usr/bin/env php
<?php
/**
 * This shell is used to batch install packages to get the database.
 */
if(!isset($argv[1]) or !is_dir($argv[1])) die("please set the packages root directory.\n");

$packagesRoot = $argv[1];
$packages = glob("$packagesRoot/*.tar.gz");
foreach($packages as $package)
{
    echo `pkg install $package true`;
}
